### ISSUE TITLE
Release new version to RubyGems

### ISSUE THREAD

**Issue by ldthorne** [runa/pry-reload#5]
Hi @runa, thanks so much for merging in my PR so quickly and for your work on this project! Would it be possible for you to release a new version on RubyGems? Hoping to include it in my project without pointing to Github.

Thanks again for your help! Let me know if I can be of any assistance.

**Comment by quintrino** [comment]
Hi @runa, any plans on releasing a new version of this onto Ruby Gems?

**Comment by munshkr** [comment]
Hi @quintrino, @ldthorne I forgot I had ownership of the gem, I've just pushed the latest as version 0.2!

**Comment by quintrino** [comment]
Thanks so much @munshkr, do you want to update the README.md to mention you're the new owner? Or is it still a joint project?
